server.port=8081

spring.data.mongodb.database=rideshare_db
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost

app.jwt.secret=ReplaceThisWithASecureRandomLongSecretKeyForProduction
app.jwt.expiration-ms=86400000

logging.level.org.springframework.security=INFO
